import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { DiscussionRoom } from '../DiscussionRoom'
import { aiApi } from '@/lib/api'

vi.mock('@/lib/api', () => ({
  aiApi: {
    multiAgent: vi.fn(),
  },
}))

const DEBATE_TEXT = [
  'Technical Analyst: BTC holds above the 200-day moving average; structure remains bullish.',
  'Risk Manager: Volatility is elevated, keep position sizing conservative and use stops.',
  'Macro Analyst: Global liquidity conditions favor risk assets this quarter.',
  'Sentiment Analyst: Funding rates show mild greed but no extreme froth.',
  'Bull Advocate: ETF inflows and the halving cycle support continued upside.',
  'Bear Advocate: A stronger dollar could pressure BTC in the near term.',
  'Consensus: The council leans bullish while advising disciplined risk control.',
].join('\n')

function mockOkResponse() {
  return {
    status: 'ok',
    strategy_name: 'MultiAgent_BTCUSDT',
    strategy_code: '# Multi-agent analysis\n# ' + DEBATE_TEXT,
    description: 'Generated by multi-agent collaboration',
    agents: { analysis: DEBATE_TEXT },
    debate_summary: DEBATE_TEXT,
  }
}

function renderPage() {
  return render(
    <MemoryRouter>
      <DiscussionRoom />
    </MemoryRouter>,
  )
}

describe('DiscussionRoom AI 多模型讨论室', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('渲染空态：默认 BTCUSDT，展示角色说明与开始按钮', () => {
    renderPage()
    expect(screen.getByText('AI 多模型讨论室')).toBeTruthy()
    expect(screen.getByText('开始讨论')).toBeTruthy()
    expect(screen.getByText('输入交易对，召集 6 位 AI 角色讨论')).toBeTruthy()
    expect((screen.getByPlaceholderText('交易对，如 BTCUSDT') as HTMLInputElement).value).toBe('BTCUSDT')
    expect(screen.queryByText('共识总结')).toBeNull()
  })

  it('发起讨论后按角色渲染观点与共识总结', async () => {
    vi.mocked(aiApi.multiAgent).mockResolvedValue(mockOkResponse() as never)
    renderPage()
    fireEvent.click(screen.getByText('开始讨论'))
    await waitFor(() => expect(screen.getByText('共识总结')).toBeTruthy())
    expect(aiApi.multiAgent).toHaveBeenCalledWith({ symbol: 'BTCUSDT' })
    expect(screen.getByText('技术分析师')).toBeTruthy()
    expect(screen.getByText('风控官')).toBeTruthy()
    expect(screen.getByText('宏观分析师')).toBeTruthy()
    expect(screen.getByText('情绪分析师')).toBeTruthy()
    expect(screen.getByText('多方辩护')).toBeTruthy()
    expect(screen.getByText('空方辩护')).toBeTruthy()
    expect(screen.getByText(/ETF inflows/)).toBeTruthy()
    expect(screen.getByText(/leans bullish/)).toBeTruthy()
  })

  it('快捷币种切换并以该 symbol 发起请求', async () => {
    vi.mocked(aiApi.multiAgent).mockResolvedValue(mockOkResponse() as never)
    renderPage()
    fireEvent.click(screen.getByText('ETHUSDT'))
    fireEvent.click(screen.getByText('开始讨论'))
    await waitFor(() => expect(aiApi.multiAgent).toHaveBeenCalledWith({ symbol: 'ETHUSDT' }))
  })

  it('请求异常时展示错误态与重试按钮', async () => {
    vi.mocked(aiApi.multiAgent).mockRejectedValue(new Error('network down'))
    renderPage()
    fireEvent.click(screen.getByText('开始讨论'))
    await waitFor(() => expect(screen.getByText('network down')).toBeTruthy())
    expect(screen.getByText('重试')).toBeTruthy()
  })

  it('status=error 时展示后端返回的 msg', async () => {
    vi.mocked(aiApi.multiAgent).mockResolvedValue({ status: 'error', msg: 'No AI provider configured.' } as never)
    renderPage()
    fireEvent.click(screen.getByText('开始讨论'))
    await waitFor(() => expect(screen.getByText('No AI provider configured.')).toBeTruthy())
  })

  it('未按角色分段的输出回退为完整记录展示', async () => {
    const blob = 'The council debated at length but returned a single unstructured paragraph about BTC.'
    vi.mocked(aiApi.multiAgent).mockResolvedValue({
      status: 'ok',
      strategy_name: 'MultiAgent_BTCUSDT',
      debate_summary: blob,
      agents: { analysis: blob },
    } as never)
    renderPage()
    fireEvent.click(screen.getByText('开始讨论'))
    await waitFor(() => expect(screen.getByText(/single unstructured paragraph/)).toBeTruthy())
    expect(screen.getAllByText('本轮未单独分段发言，详见共识总结').length).toBe(6)
  })
})
